name: CI build of the standard

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended xsltproc ghostscript cm-super librsvg2-bin inkscape
      
    - name: Build the document
      run: |
        inkscape --version
        make role_diagram.pdf biblio forcetex
      
    - name: Check the output
      run: |
        test -f DataLink.pdf
        test -f DataLink.bbl
        
    - name: Build the implementation note
      run: make --makefile=MakefileImp biblio forcetex
      
    - name: Check the output
      run: test -f DataLinkImp.pdf
        
    - uses: actions/upload-artifact@v1
      with:
        name: DataLink.pdf Preview
        path: DataLink.pdf
        
    - uses: actions/upload-artifact@v1
      with:
        name: DataLinkImp.pdf Preview
        path: DataLinkImp.pdf
